Add support for appsettings.ENVIRONMENT.json files
olsh/resharper-configuration-sense pull request #9
Opened 2018-10-25 14:01 UTC by asser-dk

I found it cumbersome manually having to add each of your `appsettings.ENVIRONMENT.json` config files for each of your projects.

With this commit files matching the pattern `appsettings.*.json` is also scanned.

I also attempted to clean up the autocomplete list by merging the values into a comma-separated string so the user can see the available options.

2018-10-26 07:55 UTC, olsh requested changes
Thank you for the PR! 👍

2018-10-26 07:55 UTC, olsh commented on src/Resharper.ConfigurationSense/Extensions/ProjectExtensions.cs
> +            var settings = new Dictionary<string, IList<string>>();
Let's use linked list here
```suggestion
            var settings = new Dictionary<string, LinkedList<string>>();
```

2018-10-26 07:55 UTC, olsh commented on src/Resharper.ConfigurationSense/Extensions/ProjectExtensions.cs
> +                    if (!settings.ContainsKey(formattedPath))
We can optimize this to access the dictionary only once with the `TryGet` method

2018-10-26 08:18 UTC, asser-dk commented
replaced the list and the dictionary access

2018-10-30 20:30 UTC, olsh commented
Thank you for the contribution 👍 
Merged in #10

2018-10-30 20:30 UTC, closed without merging